### ISSUE TITLE
Bug: 'Broker_WorldQuests' tried to call the protected function '<unnamed>:Hide()'.

### ISSUE THREAD

**Issue by 40P3** [xmyno/Broker_WorldQuests#9] opened 2016-10-06 09:28 UTC
Hi,

Thanks for the great addon. Below is a bug that I've receiving with the latest version (r23). Thanks for looking into it!
H0PE

ERROR:
1x [ADDON_ACTION_BLOCKED] AddOn 'Broker_WorldQuests' tried to call the protected function '<unnamed>:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C](?): in function `Hide'
FrameXML\WorldMapActionButton.lua:58: in function`Clear'
FrameXML\WorldMapActionButton.lua:67: in function `Refresh'
FrameXML\WorldMapActionButton.lua:19: in function`SetMapAreaID'
FrameXML\WorldMapFrame.lua:1140: in function <FrameXML\WorldMapFrame.lua:1065>
[C](?): in function `WorldMapFrame_Update'
FrameXML\WorldMapFrame.lua:2869: in function`WorldMapFrame_UpdateMap'
FrameXML\WorldMapFrame.lua:408: in function <FrameXML\WorldMapFrame.lua:394>
[C](?): in function `SetMapToCurrentZone'
FrameXML\WorldMapFrame.lua:341: in function <FrameXML\WorldMapFrame.lua:320>

[C](?): in function `Show'
FrameXML\UIParent.lua:2336: in function`SetUIPanel'
FrameXML\UIParent.lua:2138: in function `ShowUIPanel'
FrameXML\UIParent.lua:2048: in function <FrameXML\UIParent.lua:2044>
[C]: in function`SetAttribute'
FrameXML\UIParent.lua:2830: in function <FrameXML\UIParent.lua:2818>
[C](?): in function `ShowUIPanel'
FrameXML\UIParent.lua:2814: in function`ToggleFrame'
FrameXML\WorldMapFrame.lua:236: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:

**Comment by xmyno** [comment] 2016-10-14 11:46
This will probably be fixed with patch 7.1. I will take another look on PTR if it really is fixed, but a workaround would be quite extensive, so this will have to wait until then if this is the case.

It doesn't impact gameplay in any way as far as I have seen, so waiting won't be a problem I think.

**Comment by xmyno** [comment] 2016-10-26 16:30
Turns out it still happens in 7.1, but I found a simple fix.

See https://github.com/xmyno/Broker_WorldQuests/commit/344f93ef816f619129d6f55f528286ceefc76bd4, will be in next release.

**Comment by ceylina** [comment] 2017-02-06 17:46
Want to add on to this as I just noticed I had a taint log (without setting a taint level).

2/5 15:43:31.205  CloseDropDownMenus()
2/5 15:43:31.205  An action was blocked in combat because of taint from Broker_WorldQuests - <unnamed>:Hide()
2/5 15:43:31.205      Interface\FrameXML\WorldMapActionButton.lua:58 <unnamed>:Clear()
2/5 15:43:31.205      Interface\FrameXML\WorldMapActionButton.lua:67 <unnamed>:Refresh()
2/5 15:43:31.205      Interface\FrameXML\WorldMapActionButton.lua:19 <unnamed>:SetMapAreaID()
2/5 15:43:31.205      Interface\FrameXML\WorldMapFrame.lua:418
2/5 15:43:31.205      WorldMapFrame:Hide()
2/5 15:43:31.205      Interface\FrameXML\UIParent.lua:2358 <unnamed>:SetUIPanel()
2/5 15:43:31.205      Interface\FrameXML\UIParent.lua:2385 <unnamed>:MoveUIPanel()
2/5 15:43:31.205      Interface\FrameXML\UIParent.lua:2416 <unnamed>:HideUIPanel()
2/5 15:43:31.205      Interface\FrameXML\UIParent.lua:2090
2/5 15:43:31.205      <unnamed>:SetAttribute()
2/5 15:43:31.205      Interface\FrameXML\UIParent.lua:2884 HideUIPanel()
2/5 15:43:31.205      Interface\FrameXML\WorldMapFrame.lua:329

**Comment by Cluuey** [comment] 2017-02-24 20:55
I've been looking into this as it's been driving me nuts, it must be the way I play as I get it a lot.
I tend to open the map a lot to navigate and don't care that I'm riding through mobs, gogo bear spec!

In my investigation I came across two posts which might prove useful to you:
http://www.wowinterface.com/forums/showthread.php?t=54247

And an ElvUI commit where they manage to avoid tainting the map:
http://git.tukui.org/Elv/elvui/commit/fd92da18c087d089bd502f1ca6ab4287401ad098

Not sure you'll be able to get around it because you need to check the map to see if there are new quests, however are you able to check to see if we're in combat first and if we are don't do that check?
I guess that doesn't stop us opening the map out of combat, riding into mobs, closing the map, which would cause the update to fire and taint it? (I think)

I'm far, far ----------------------------------------------far from a beginner, not even close to an expert.

**Comment by xmyno** [comment] 2017-03-30 05:45
I removed the open world map on row click with 7.2.31. That should hopefully resolve the ADDON_ACTION_BLOCKED for the instant world quest button. But I have also seen this specific error caused by things like Aurora (addon to customize default UI look).

**Comment by Cluuey** [comment] 2017-04-01 16:46
Okay this is getting stranger.
I got the following error while on a gryphon. I had the Class Hall report window open, as I changed map zones this popped up.
So:
Not in combat.
Not looking at the map.
Error pops up.
I don't even think I had the broker list open, I was checking how long until my artifact research finished.

Edit. I should mention that I've had other errors too but I suspect you're getting them too. I can look for one in my Swatter log if you want?

```Date: 2017-04-01 22:40:12
ID: -2
Error occured in: AddOn: Broker_WorldQuests
Count: 20
Message: Note: AddOn Broker_WorldQuests attempted to call a protected function (<unnamed>:Hide()) during combat lockdown.
Debug:
   [C]: Hide()
   ..\FrameXML\WorldMapActionButton.lua:58: Clear()
   ..\FrameXML\WorldMapActionButton.lua:67: Refresh()
   ..\FrameXML\WorldMapActionButton.lua:19: SetMapAreaID()
   ..\FrameXML\WorldMapFrame.lua:428:
      ..\FrameXML\WorldMapFrame.lua:390
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: Hide()
   ..\FrameXML\UIParent.lua:2404: SetUIPanel()
   ..\FrameXML\UIParent.lua:2431: MoveUIPanel()
   ..\FrameXML\UIParent.lua:2462: HideUIPanel()
   ..\FrameXML\UIParent.lua:2136:
      ..\FrameXML\UIParent.lua:2128
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:2930:
      ..\FrameXML\UIParent.lua:2917
   [C]: HideUIPanel()
   ..\FrameXML\UIParent.lua:3098: CloseWindows()
   ..\FrameXML\UIParent.lua:3137:
      ..\FrameXML\UIParent.lua:3127
   [C]: securecall()
   ..\FrameXML\UIParent.lua:3748: ToggleGameMenu()
   [string "TOGGLEGAMEMENU"]:1:
      [string "TOGGLEGAMEMENU"]:1
Locals:
None
AddOns:
  MoncaiCompare, v7.0.1
  Swatter, v7.2.5688 (TasmanianThylacine)
  AdvancedInterfaceOptions, v1.1.3
  AngryAssignments, vv1.8.9
  AskMrRobot, v50
  AucAdvanced, v7.2.5688 (TasmanianThylacine)
  AucFilterBasic, v7.2.5688 (TasmanianThylacine)
  AucFilterOutlier, v7.2.5688.5459(7.2/embedded)
  AucMatchUndercut, v7.2.5688.5585(7.2/embedded)
  AucScanData, v7.2.5688 (TasmanianThylacine)
  AucStatHistogram, v7.2.5688 (TasmanianThylacine)
  AucStatiLevel, v7.2.5688 (TasmanianThylacine)
  AucStatPurchased, v7.2.5688 (TasmanianThylacine)
  AucStatSales, v7.2.5688.5598(7.2/embedded)
  AucStatSimple, v7.2.5688 (TasmanianThylacine)
  AucStatStdDev, v7.2.5688 (TasmanianThylacine)
  AucStatWOWEcon, v7.2.5688.5613(7.2/embedded)
  AucUtilAHWindowControl, v7.2.5688.5575(7.2/embedded)
  AucUtilAppraiser, v7.2.5688.5666(7.2/embedded)
  AucUtilAskPrice, v7.2.5688.5599(7.2/embedded)
  AucUtilAutoMagic, v7.2.5688.5686(7.2/embedded)
  AucUtilCompactUI, v7.2.5688.5629(7.2/embedded)
  AucUtilEasyBuyout, v7.2.5688.5576(7.2/embedded)
  AucUtilFixAH, v7.2.5688 (TasmanianThylacine)
  AucUtilItemSuggest, v7.2.5688.5651(7.2/embedded)
  AucUtilPriceLevel, v7.2.5688.5633(7.2/embedded)
  AucUtilScanButton, v7.2.5688.5631(7.2/embedded)
  AucUtilScanFinish, v7.2.5688.5588(7.2/embedded)
  AucUtilScanProgress, v7.2.5688.4979(7.2/embedded)
  AucUtilScanStart, v7.2.5688.5347(7.2/embedded)
  AucUtilSearchUI, v7.2.5688.5672(7.2/embedded)
  AucUtilSimpleAuction, v7.2.5688.5654(7.2/embedded)
  AucUtilVendMarkup, v7.2.5688.4828(7.2/embedded)
  AutoLootSpecSwap, v
  Babylonian, v5.1.DEV.332(/embedded)
  BattlePetBreedID, vr143
  BeanCounter, v7.2.5688 (TasmanianThylacine)
  BonusRollPreview, v70200.38-Release
  BrokerEquipment, v70100.27-Release
  BrokerRunSpeed, v1.6
  BrokerWorldQuests, v7.2.32
  BrokerDualSpec, v7.06
  Chatter, v1.5.3-1-gd0ab21b
  ChefsHat, v7.0.0.160807
  Clique, vv70100-1.1.0-bec043c
  CollectMe, v2.9.3
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.2.0
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  epgp, vv5.12.12
  epgplootmaster, v6.71
  epgplootmasterml, v6.71
  EventHorizon, v1.9.19
  EventHorizonDruid, v
  Examiner, v16.08.30
  ExtraQuestButton, v70000.8-Release
  FamilyFamiliarHelper, v1.0.4
  HandyNotes, vv1.4.13
  HandyNotesLegionTreasures, v1
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarTelemancy, v1
  HandyNotesTreasureHunter, v1
  IceHUD, v1.10.15
  Informant, v7.2.5688 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.416(/embedded)
  MinimapMouseWheelEnabler, v
  MoveAnything, v16.1.7
  NinjaPanel, vv60100-1.0.0
  nPlates, v2.20
  Postal, vv3.5.8
  Recap, v4.92
  Rematch, v4.6.4
  RSA, v3.275
  RSADruid, v
  SexyMap, vv7.2.0
  Simulationcraft, v1.5.1
  Stubby, v7.2.5688 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  TipTop, v2.18
  TomTom, vv70100-1.1.0-49459b0
  WeakAuras, v2.3.8
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=b69)

**Closed as completed** 2020-10-19 20:44 UTC
